### ISSUE TITLE
Wrapping a div around an img tag results in a new line

### ISSUE THREAD

**Issue by ronyland** [MatteoGabriele/vue-progressive-image#64]
div property is block，
but img property is inline。
Replacing <img> with <div><img /></div> will cause the style to get messy

**Comment by kgnfth** [comment]
this fixed it for me

```css
.progressive-image {
  position: unset !important;
}
```
